const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({baseURL:process.env.REVIEW_URL || 'http://127.0.0.1:8873',viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.REVIEW_URL || 'http://127.0.0.1:8873');
 await page.locator('#changes button').first().waitFor();
 const initial=await (await page.request.get('/api/state')).json();
 await page.request.post('/api/update',{headers:{'X-Tracker-Token':initial.token},data:{revision:initial.revision,action:'assumptions',assumptions:[]}});
 await page.reload();
 await page.locator('#changes button').first().waitFor();
 await page.locator('#changes button').first().click();
 if(await page.locator('mark').count()===0) throw Error('No highlighted edits');
 await page.getByLabel('Analyst note').fill('Browser verification only');
 await page.getByLabel('Status',{exact:true}).selectOption('accepted');
 await page.getByRole('button',{name:'Save decision',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Saved locally.'}).waitFor();
 await page.reload();
 await page.getByLabel('Analyst note').waitFor();
 if(await page.getByLabel('Analyst note').inputValue()!=='Browser verification only') throw Error('Note did not persist');
 await page.getByText('Investment assumptions',{exact:true}).click();
 await page.getByRole('button',{name:'Add assumption',exact:true}).click();
 await page.getByLabel('Assumption',{exact:true}).fill('Supplier concentration remains manageable');
 await page.getByLabel('Terms (comma separated)').fill('supplier');
 const saved=page.waitForResponse(r=>r.url().endsWith('/api/update')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save assumptions',exact:true}).click();
 if(!(await saved).ok())throw Error('Assumption save failed');
 await page.getByText('Review session and history',{exact:true}).click();
 await page.getByLabel('Reviewer name').fill('Browser test, not human evidence');
 await page.getByRole('button',{name:'Start session',exact:true}).click();
 await page.locator('#session-list').filter({hasText:'Running'}).waitFor();
 await page.getByRole('button',{name:'Finish session',exact:true}).click();
 await page.locator('#session-list').filter({hasText:'seconds'}).waitFor();
 await page.getByText('Correct the matching',{exact:true}).click();
 const matchSaved=page.waitForResponse(r=>r.url().endsWith('/api/update')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save matching',exact:true}).click();
 if(!(await matchSaved).ok())throw Error('Matching save failed');
 const link=await page.locator('#detail a').first().getAttribute('href');
 const source=await page.request.get(link);
 if(!source.ok())throw Error('Broken citation');
 await page.screenshot({path:process.env.SCREENSHOT_PATH || '/private/tmp/filing-review.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 await page.goto((process.env.REVIEW_URL || 'http://127.0.0.1:8873')+'/manual');
 await page.getByRole('heading',{name:'Manual source reading'}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({passed:true,checks:['highlighted edits','decision persistence','assumption save','session start and finish','matching correction','citation HTTP','mobile layout','manual source view'],consoleErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
